#!/bin/bash
IN="in"
OUT="out"
GOOD="good"
for index in {1..2}
do
    echo "--- Starting cw test$index ----------"
    rm -f $OUT/out$index $OUT/err$index
    echo "Running: ../cw <$IN/test$index > $OUT/out$index 2> $OUT/err$index"
    ../cw <$IN/test$index > $OUT/out$index 2> $OUT/err$index
    echo cw test$index diff
    diff $GOOD/out$index $OUT/outC$index
    diff $GOOD/err$index $OUT/errC$index
    echo "--- Ending ccw test$index ----------"
done
echo All Done
